### ISSUE TITLE
Classpath issues

### ISSUE THREAD

**Issue by aurae** [aurae/android-junit5#10]
I'm still getting some classpath-related errors when either trying to run the JUnit 5 Gradle task, or using AS' built-in "Run Tests" feature. In some projects, only one of the methods works, other times, both do. It has to be related to the way the classpath is set up & prepared for unit tests.

**Comment by aurae** [comment]
Addressed in 1.0.0-M4-rev2.

**Comment by jschamburger** [comment]
Unfortunately, I still have problems (with 1.0.0-M4-rev2) regarding classpath when starting tests (for now, I only have legacy JUnit 4 tests) from Android Studio (tried both 2.4 and 3.0 Canary 3). From the command-line, the tests run just fine, but in Android Studio, I get `ClassNotFoundException`s for `net.sqlcipher.database.SQLiteOpenHelper` and `com.roughike.bottombar.OnTabClickListener` (library dependency). The setup in the README.MD should be enough, right?

**Comment by aurae** [comment]
Thanks for reporting back. Are you on AGP 2.x or 3.x when you run into this? Does changing to the other work? I'm going to investigate further.

**Comment by jschamburger** [comment]
Thanks! I tried it with Android Studio 2.4 Preview and 3.0 Canary 3; both didn't work.
But the problem might be caused by a dependency aar in a separate module. I'll investigate some more, maybe the issue is in my setup. 
I tried running the sample project https://github.com/StylingAndroid/JUnit5/tree/Kotlin with updated dependency and it worked just fine.

**Comment by aurae** [comment]
I'm seeing the same inconsistent behavior between different projects as well, although it's usually the cmd version that won't run, while the IDE is unaffected. I have looked into hooking into the default setup performed by the Android Gradle Plugin for unit tests directly, to leverage the classpath setup they've got going on. It isn't trivial though, since JUnit 5 relies on a `JavaExec` task at the moment, which we'd need to combine with AGP's `AndroidUnitTest` task type.

**Comment by jschamburger** [comment]
Alright, I just verified that the problem was caused by an .aar library which was imported as a separate module (using the steps described here https://stackoverflow.com/questions/29826717/how-to-import-a-aar-file-into-android-studio-1-1-0-and-use-it-in-my-code). 

After importing the .aar file using a local repository fixed it and now all tests are running both in AS and on the command-line.
I added
`repositories {
    flatDir {
        dirs 'libs'
    }
}`
on top level and
`compile (name:'bottom-bar-release', ext:'aar')`
to the dependencies.

It is worth noting that I also added the line 
`testProvided "org.junit.vintage:junit-vintage-engine:4.12.0-M4"` which I got from the StylingAndroid example.

**Comment by aurae** [comment]
I'm glad you got it working! As of `1.0.0-M4-rev1`, the Vintage Engine is supposed to be [automatically applied to the runtime classpath](https://github.com/aurae/android-junit5/blob/10c2dbc5b5fd13e7ff901e2c4ba19142b36b18e3/android-junit5/src/main/groovy/de/mannodermaus/gradle/anj5/AndroidJUnitPlatformPlugin.groovy#L73) when you apply the `android-junit5` plugin. Can you verify that your tests still run if you remove the `testProvided` dependency again?

**Comment by jschamburger** [comment]
Without the dependency, the tests are not running from Android Studio unfortunately:
`Exception in thread "main" java.lang.NoClassDefFoundError: org/junit/platform/engine/EngineExecutionListener
	at org.junit.platform.launcher.core.LauncherFactory.create(LauncherFactory.java:53)
	at com.intellij.junit5.JUnit5IdeaTestRunner.createListeners(JUnit5IdeaTestRunner.java:39)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:49)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.ClassNotFoundException: org.junit.platform.engine.EngineExecutionListener
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 5 more`

On the command-line, they are running fine though.

Forgot to mention earlier: I'm using the Android Gradle Plugin 2.2.3.

**Comment by aurae** [comment]
Got it, thanks! I suppose the IDE requires the dependency to be available at compile time, too, even though a `TestEngine` is supposed to be driving execution at runtime only - hence why the runtime dependency is not enough, and a compile-only dependency using `provided` is necessary as well.

**Comment by aurae** [comment]
Actually, looking at the stack trace, it's not so much a class specific to the Vintage Engine that's failing, but the ExecutionListener itself.

Can you try exchanging the `provided` dependency to `org.junit.vintage:junit-platform-engine:1.0.0-M4` instead?

**Comment by jschamburger** [comment]
Using that dependency, the tests are running fine in AS and on command-line.

**Comment by aurae** [comment]
I will amend the dependency issue for the next revision, so you won't have to add anything on top of what the plugin provides. Thanks for your efforts!

**Comment by jschamburger** [comment]
Great, thank you for all the work on this plugin!

**Comment by aurae** [comment]
Instead of trying to duplicate the work that the Gradle plugin does in terms of classpath aggregation, it would probably be way more reasonable to simply share the default `test` tasks' classpath altogether. This should be fairly simple if we consider that Gradle's Test tasks expose their classpath publicly. Adding the `junitPlatform` configuration at the end should do the trick...

**Comment by aurae** [comment]
Addressed in 1.0.0-M4-rev3.
